#!/usr/bin/env bash
# Checks every claim about LYGIA's Metal files on this Mac's GPU and writes
# test/msl/proof/RESULTS.md:
#
#   compile   how many .msl files compile, before and after (compile.sh)
#   linking   two .metal files in one target, code size, options, helper
#             library (linking.sh)
#   package   a Swift package with two .metal files (package/run.sh)
#   values    each fix, compared with GLSL or known values (proof.py)
#
# "before" is upstream main unless a claim says otherwise. Requires macOS with
# Xcode, glslang and spirv-cross (brew install glslang spirv-cross).
#
# usage: test/msl/proof/proof.sh [before ref (default origin/main)]
set -euo pipefail
PROOF="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(cd "$PROOF/../../.." && pwd)"
BEFORE="${1:-origin/main}"
OUT="$PROOF/RESULTS.md"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

# compile.sh on the files at BEFORE: copy it next to them, so it compiles those.
mkdir -p "$TMP/before/test/msl"
git -C "$ROOT" archive "$BEFORE" -- ':(glob)**/*.msl' | tar -x -C "$TMP/before"
cp "$ROOT/test/msl/compile.sh" "$TMP/before/test/msl/"
summary() { grep -E '^(MSL:|FAIL (combined|linking))' | sed 's/^/- /'; }
echo "compile.sh (before)..."
before_compile=$("$TMP/before/test/msl/compile.sh" 2>&1 | summary || true)
echo "compile.sh (after)..."
after_compile=$("$ROOT/test/msl/compile.sh" 2>&1 | summary || true)
echo "linking.sh..."
linking=$("$PROOF/linking.sh" "$BEFORE" 2>/dev/null)
echo "package/run.sh..."
package=$("$PROOF/package/run.sh" "$BEFORE" 2>/dev/null | sed 's/ *$//; s/\*\* BUILD SUCCEEDED \*\*/builds/; s/\*\* BUILD FAILED \*\* */fails: /; s/^/- /')
echo "proof.py..."
set +e
"$PROOF/proof.py" --markdown "$TMP/claims.md"
status=$?
set -e

head=$(git -C "$ROOT" rev-parse --short HEAD)
[ -n "$(git -C "$ROOT" status --porcelain -- '*.msl' test/msl)" ] && head="$head with uncommitted changes"
before_head=$(git -C "$ROOT" rev-parse --short "$BEFORE")
gpu=$(system_profiler SPDisplaysDataType 2>/dev/null | sed -n 's/.*Chipset Model: //p' | head -1)
metal=$(xcrun -sdk macosx metal --version 2>/dev/null | head -1)

cat > "$OUT" <<EOF
# LYGIA Metal: claims checked on the GPU

Generated by \`test/msl/proof/proof.sh\` on $(date +%Y-%m-%d), at $head, against $BEFORE ($before_head). $gpu, macOS $(sw_vers -productVersion), $metal. Don't edit by hand; run the script again.

## Every .msl file compiles

\`test/msl/compile.sh\` compiles each .msl file on its own, then all of them in one file (each included twice, to check the include guards), then links two such files.

Before ($BEFORE):

$before_compile

After:

$after_compile

## Linking (lygia#322)

$linking

## Swift package

\`test/msl/proof/package\` is a Swift package with LYGIA's .msl files and two .metal files that include generative/fbm.msl, each with a SwiftUI \`[[stitchable]]\` function. Xcode compiles a package's .metal files into its bundle's default.metallib, which SwiftUI loads with \`ShaderLibrary.bundle(.module)\`. Each line is a clean \`xcodebuild\`:

$package

Not checked: loading the functions at runtime on a device.

## Values

Each claim runs a snippet on the GPU three times: with LYGIA's GLSL (compiled with glslang and translated to Metal with spirv-cross), with the Metal files before the fix, and with the Metal files after. The reference is GLSL, or expected values when GLSL has the same bug (then the values come from the math: a property such as "the weights sum to 1", or a known result). A claim is shown when Metal after matches the reference and Metal before doesn't.

$(cat "$TMP/claims.md")

## Not shown here

- **worley**: the Metal \`worley()\` already returned the same values as GLSL; the update added \`worley2\` (shown above) and the WORLEY_JITTER and WORLEY_DIST_FNC options.
- **fisheye2xyz at the center**: \`ndc / R\` is 0 / 0 (NaN), but on this GPU the result is still (0, 1, 0), with or without fast math, so the guard taken from WESL changes nothing here.
- **Need a texture**, not covered yet: filter/laplacian's w8 and w12 kernels, filter/sharpen/adaptive, and sample/equirect, smooth and fxaa.
- **Need a lit scene**, not covered yet: gooch's shadow direction, pbrClearCoat's clear coat normal, light/spot's options and smoothstep order, and raymarch/glass.
EOF
echo "wrote $OUT"
exit $status
